# -*- coding: utf-8 -*-

"""harvest seven letter words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BrGqPn-hQRxRMCjtdMYUTczOlOyvY5O-
"""
import time
ltime=time.time()
File2='/home/sam/Desktop/github repositorys/will-0.github.io/other_cool_stuff/scrabble-hacker/output.txt'
File='/home/sam/Desktop/github repositorys/will-0.github.io/other_cool_stuff/scrabble-hacker/words_alpha.txt'
def fileline(file,line):
  f = open(file, 'r')
  for i in range(line):
    f.readline()
  return f.readline()
  f.close()
  
def fileappend(file,app):
  f = open(file, 'a')
  f.write(app)
  f.close()
def filelen(File):
  f = open(File, "r")
  nonempty_lines = [line.strip("\n") for line in f if line != "\n"]
  line_count = len(nonempty_lines)
  f.close()
  return line_count
fl=filelen(File)
flarr=[]
print(fl)
for i in range(fl):
  if len(fileline(File,i).replace('\n',''))<=8:
    flarr.append(fileline(File,i).replace('\n',''))
  if i%10000==0:
    print('percentage: ',str((i/fl)*100))
    print('seconds to complete 10000 words: '+str(time.time()-ltime))
    ltime=time.time()
f = open(File2, 'w')
f.write(str(flarr))
f.close()